# Generated by Django 4.2.5 on 2023-09-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='질문의 제목', max_length=200)),
                ('content', models.TextField(help_text='질문의 내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='질문을 작성한 일시')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='답변의 내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='답변을 작성한 일시')),
                ('question', models.ForeignKey(help_text='질문', on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
