# Generated by Django 4.1.1 on 2022-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
